### ISSUE TITLE
Warning: Unable to preventDefault inside passive event listener due to target being treated as passive.

### ISSUE THREAD

**Issue by leroy-p** [chrisbateman/impetus#30]
This warning appears in my console (Chrome version 58.0.3029.110 64-bit) when I am scrolling in my app using Impetus.js

**Comment by chrisbateman** [comment]
This should fix it for now, but it sounds like Chrome would also prefer for you to add a `touch-action: none` CSS property to the element. We could do that directly from Impetus, but I'm kind of reluctant to do it since we don't know if it might get blown away by something the consumer is doing.

**Comment by romellem** [comment]
I actually don't know if the changes made in d5d023aa6085f5a46637f31bb823f94ac21cdac5 work.

Per the [documentation on the `passive` option](https://github.com/WICG/EventListenerOptions/blob/gh-pages/explainer.md):

> By marking a touch or wheel listener as `passive`, **the developer is promising the handler won't call `preventDefault` to disable scrolling**. This frees the browser up to respond to scrolling immediately without waiting for JavaScript, thus ensuring a reliably smooth scrolling experience for the user.

We _do_ call `preventDefault` within `onMove`, so I'm sure what benefit this is giving.

It is confusing though, since the browser [should also](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener) emit an error when calling `preventDefault` from within a passive handler:

> If a passive listener does call `preventDefault()`, the user agent will do nothing other than generate a console warning.

Overall this probably doesn't hurt anything, and maybe does improve things.

Either way, the documentation on Passive Event Listeners is a bit confusing in cases where we do call `preventDefault`.
