### ISSUE TITLE
Add an"snapToGrid"-option

### ISSUE THREAD

**Issue by yckart** [chrisbateman/impetus#7]
It would nice to see a way, to get the "finish"-offset (where the "movement" **will** end). So we could calculate the closest offset (compared to our grid) and scroll to it (manullay?).

**Comment by chrisbateman** [comment]
This probably isn't going to happen, for a couple reasons:
- This library currently doesn't compensate for slow frame rates, as a tradeoff for simplicity and size. Since it just calculates deceleration as it goes, we don't know exactly where it will end. We could try to estimate - but it might not be precisely accurate if the frame rate drops. I'm not opposed to improving this (if it can be done relatively simply), but...
- If you're getting into snapping behavior, you'd probably be much better off using something along the lines of [Impulse](http://impulse.luster.io/).
